"""Merge the two reviewer JSON outputs into one per-sample report + a cohort CSV row."""
from __future__ import annotations

import csv
import os


def build_report(evidence: dict, claude: dict, gemini: dict, out_md: str, out_csv: str) -> dict:
    sample_id = evidence["sample_id"]
    ranked = evidence["all_candidates_ranked"]
    raw_top = ranked[0]
    top_n = evidence["top_candidates_with_segment_metrics"]

    consensus_agree = claude["recommended_candidate_id"] == gemini["recommended_candidate_id"]
    consensus_candidate = claude["recommended_candidate_id"] if consensus_agree else None
    human_review = bool(claude.get("human_review_needed")) or bool(gemini.get("human_review_needed"))

    status = "Consensus" if consensus_agree else "Discordant review"
    if human_review:
        status += " -- human review recommended"

    row = {
        "sample_id": sample_id,
        "raw_titan_optimal_candidate": raw_top["candidate_id"],
        "raw_titan_ploidy": raw_top["ploidy"],
        "raw_titan_purity": raw_top["titan_purity"],
        "raw_titan_sdbw": raw_top["s_dbw_both"],
        "claude_candidate": claude["recommended_candidate_id"],
        "claude_ploidy": claude["recommended_ploidy"],
        "claude_purity": claude["recommended_titan_purity"],
        "claude_confidence": claude.get("confidence"),
        "claude_overrides_raw": claude.get("overrides_raw_titan_optimal"),
        "claude_comment": (claude.get("comment") or "").replace("\n", " ")[:600],
        "gemini_candidate": gemini["recommended_candidate_id"],
        "gemini_ploidy": gemini["recommended_ploidy"],
        "gemini_purity": gemini["recommended_titan_purity"],
        "gemini_confidence": gemini.get("confidence"),
        "gemini_overrides_raw": gemini.get("overrides_raw_titan_optimal"),
        "gemini_comment": (gemini.get("comment") or "").replace("\n", " ")[:600],
        "consensus_candidate": consensus_candidate or "DISCORDANT",
        "consensus_ploidy": claude["recommended_ploidy"] if consensus_agree else "",
        "consensus_purity": claude["recommended_titan_purity"] if consensus_agree else "",
        "human_review_needed": human_review,
        "status": status,
    }

    os.makedirs(os.path.dirname(out_csv) or ".", exist_ok=True)
    write_header = not os.path.exists(out_csv)
    with open(out_csv, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(row.keys()))
        if write_header:
            w.writeheader()
        w.writerow(row)

    lines = []
    lines.append(f"# TITAN Curation Report -- {sample_id}\n")
    lines.append("Generated by the TitanCNA Curation Agent CLI "
                  "(deterministic parsing + independent Claude + Gemini review).\n")

    lines.append("## Summary\n")
    lines.append("| Sample | Raw TITAN optimal (S_Dbw) | Raw purity | Claude rec. | Claude purity | "
                  "Gemini rec. | Gemini purity | Consensus | Status |")
    lines.append("|---|---|---:|---|---:|---|---:|---|---|")
    lines.append(
        f"| {sample_id} | {raw_top['candidate_id']} | {raw_top['titan_purity']} | "
        f"{claude['recommended_candidate_id']} | {claude['recommended_titan_purity']} | "
        f"{gemini['recommended_candidate_id']} | {gemini['recommended_titan_purity']} | "
        f"{consensus_candidate or 'DISCORDANT'} | {status} |\n"
    )

    lines.append("## Candidate detail\n")
    lines.append("| Rank | Candidate | Ploidy | Clusters | Purity | S_Dbw | Log-lik | "
                  "Genome altered | Subclonal | Segments | Claude verdict | Gemini verdict |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---|")
    claude_verdicts = {c["candidate_id"]: c["verdict"] for c in claude.get("ranked_candidates", [])}
    gemini_verdicts = {c["candidate_id"]: c["verdict"] for c in gemini.get("ranked_candidates", [])}
    for c in top_n:
        sm = c.get("segment_metrics") or {}
        fga = sm.get("fraction_genome_altered")
        fsc = sm.get("fraction_genome_subclonal")
        loglik = c["log_likelihood"]
        lines.append(
            f"| {c['s_dbw_rank']} | {c['candidate_id']} | {c['ploidy']} | {c['requested_num_clusters']} | "
            f"{c['titan_purity']} | {c['s_dbw_both']} | {loglik:.0f} | "
            f"{fga:.1%} | {fsc:.1%} | {sm.get('num_segments')} | "
            f"{claude_verdicts.get(c['candidate_id'], '-')} | {gemini_verdicts.get(c['candidate_id'], '-')} |"
        )
    lines.append("")

    lines.append("## Reviewer comments\n")
    lines.append(f"### Claude ({claude.get('confidence')} confidence, "
                  f"overrides raw optimum: {claude.get('overrides_raw_titan_optimal')})\n")
    lines.append((claude.get("comment") or "") + "\n")
    lines.append(f"### Gemini ({gemini.get('confidence')} confidence, "
                  f"overrides raw optimum: {gemini.get('overrides_raw_titan_optimal')})\n")
    lines.append((gemini.get("comment") or "") + "\n")

    lines.append("## Flags\n")
    all_flags = [("claude", f) for f in claude.get("flags", [])] + [("gemini", f) for f in gemini.get("flags", [])]
    if all_flags:
        lines.append("| Reviewer | Type | Severity | Evidence |")
        lines.append("|---|---|---|---|")
        for reviewer, f in all_flags:
            lines.append(f"| {reviewer} | {f.get('type')} | {f.get('severity')} | {f.get('evidence')} |")
    else:
        lines.append("No flags raised.")
    lines.append("")

    lines.append("## Human review focus\n")
    for item in claude.get("human_review_focus", []) or []:
        lines.append(f"- (Claude) {item}")
    for item in gemini.get("human_review_focus", []) or []:
        lines.append(f"- (Gemini) {item}")
    lines.append("")
    lines.append(f"**Overall human review needed: {'Yes' if human_review else 'No'}**\n")

    os.makedirs(os.path.dirname(out_md) or ".", exist_ok=True)
    with open(out_md, "w") as f:
        f.write("\n".join(lines))

    return row
